### PR TITLE
fix(packages/app): Sidecar not showing content when it's opened in the full-screen mode

### LINKED ISSUE #2788: Maximize sidecar Issue
**Describe the bug**
Maximizing the sidecar will not populate the "Summary" Tab

**Steps to reproduce the behavior**

1. Kubectl get pods -n kube-system
2. select item in table
3. expand sidecar
4. exit sidecar
5. select item in table -> summary tab doesn't load

It seems like clicking on another tab(ex: Containers), and then back to summary will work. But not all the time

**Screenshots**
Screen Shot 2019-09-16 at 4 41 48 PM

Problem also causes this greybox to appear on Firefox:
Screen Shot 2019-09-16 at 4 40 03 PM

### PR DESCRIPTION
**Pull request by myan9**
Fixed this issue by removing the transition effect of Sidecar resizing

Fixes #2788

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Please confirm that your PR fulfills these requirements

- [x] Multiple commits are squashed into one commit.
- [x] The commit message follows [Conventional Commits](https://github.com/IBM/kui/blob/master/CONTRIBUTING.md#conventional-commits), which allows us to autogenerate release notes; e.g. `fix(plugins/plugin-k8s): fixed annoying bugs`
- [x] All npm dependencies are pinned.

### CODE REVIEW

File: packages/app/src/webapp/views/sidecar.ts [hunk 1]
```diff
@@ -1002,7 +1002,7 @@ const setVisible = (sidecar: Sidecar) => {
 
   scrollIntoView()
 
-  setTimeout(() => eventBus.emit('/sidecar/toggle', { sidecar, tab }), 600)
+  eventBus.emit('/sidecar/toggle', { sidecar, tab })
```
Comment (starpit) [inline packages/app/src/webapp/views/sidecar.ts]: we need the setTimeout, but the timeout value can probably be zero

File: packages/app/src/webapp/views/sidecar.ts [hunk 2]
```diff
@@ -403,7 +403,7 @@ export const setMaximization = (tab: Tab, op = 'add', cause: MaximizationCause =
   }
 
   tab.classList[op]('sidecar-full-screen')
-  setTimeout(() => eventBus.emit('/sidecar/maximize'), 850)
+  eventBus.emit('/sidecar/maximize')
```
Comment (starpit) [inline packages/app/src/webapp/views/sidecar.ts]: we need the setTimeout, but the timeout value can probably be zero

File: packages/app/src/webapp/views/sidecar.ts (hunk 1 above)
Comment (myan9) [reply packages/app/src/webapp/views/sidecar.ts]: updated thanks!

File: packages/app/src/webapp/views/sidecar.ts (hunk 2 above)
Comment (myan9) [reply packages/app/src/webapp/views/sidecar.ts]: updated, thanks!
