### PR TITLE
fix: apache-composer

### LINKED ISSUE #5: error logged during npm install
During `npm install`, I noticed the following errors.

```
src/lib/cmds/edit-amd.ts:42:52 - error TS2307: Cannot find module '../../../../apache-composer/plugin/lib/utility/compile'.

42 import { compileSource, sourceToComposition } from '../../../../apache-composer/plugin/lib/utility/compile'
                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! editor@1.0.0 postinstall: `../../../../node_modules/.bin/tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the editor@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rabbah/.npm/_logs/2018-11-29T20_18_19_578Z-debug.log
src/test/composer1/wskflow_tests.ts:200:43 - error TS2345: Argument of type '() => Client<boolean>' is not assignable to parameter of type '() => boolean | Promise<boolean> | (Client<RawResult<any>> & RawResult<any>)'.
  Type 'Client<boolean>' is not assignable to type 'boolean | Promise<boolean> | (Client<RawResult<any>> & RawResult<any>)'.
    Type 'Client<boolean>' is not assignable to type 'Client<RawResult<any>> & RawResult<any>'.
      Type 'Client<boolean>' is not assignable to type 'Client<RawResult<any>>'.
        Type 'boolean' is not assignable to type 'RawResult<any>'.

200     .then(() => this.app.client.waitUntil(() => {
                                              ~~~~~~~

src/test/composer1/zzz-bottom-bar-back-button.ts:69:21 - error TS2531: Object is possibly 'null'.

69       .then(path => path.substring(path.lastIndexOf('/') + 1))
                       ~~~~

src/test/composer1/zzz-bottom-bar-back-button.ts:69:36 - error TS2531: Object is possibly 'null'.

69       .then(path => path.substring(path.lastIndexOf('/') + 1))
                                      ~~~~

src/test/composer1/zzz-bottom-bar-back-button.ts:83:21 - error TS2531: Object is possibly 'null'.

83       .then(path => path.substring(path.lastIndexOf('/') + 1))
                       ~~~~

src/test/composer1/zzz-bottom-bar-back-button.ts:83:36 - error TS2531: Object is possibly 'null'.

83       .then(path => path.substring(path.lastIndexOf('/') + 1))
                                      ~~~~

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @shell/apache-composer@0.5.2 postinstall: `../../../../node_modules/.bin/tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @shell/apache-composer@0.5.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rabbah/.npm/_logs/2018-11-29T20_18_19_723Z-debug.log
src/lib/flowCommand.ts:23:26 - error TS2307: Cannot find module '../../../apache-composer/plugin/lib/utility/ast'.

23 import * as astUtil from '../../../apache-composer/plugin/lib/utility/ast'
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/lib/preview.ts:34:25 - error TS2307: Cannot find module '../../../apache-composer/plugin/lib/utility/badges'.

34 import * as badges from '../../../apache-composer/plugin/lib/utility/badges'
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/lib/preview.ts:35:27 - error TS2307: Cannot find module '../../../apache-composer/plugin/lib/utility/messages'.

35 import * as messages from '../../../apache-composer/plugin/lib/utility/messages'  // TODO: import from plugin js file
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/lib/preview.ts:38:30 - error TS2307: Cannot find module '../../../apache-composer/plugin/lib/utility/compile'.

38 import * as compileUtil from '../../../apache-composer/plugin/lib/utility/compile'
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/lib/util.ts:18:26 - error TS2307: Cannot find module '../../../apache-composer/plugin/lib/utility/ast'.

18 import * as astUtil from '../../../apache-composer/plugin/lib/utility/ast'
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/lib/util.ts:19:25 - error TS2307: Cannot find module '../../../apache-composer/plugin/lib/utility/badges'.

19 import * as badges from '../../../apache-composer/plugin/lib/utility/badges'
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @shell/wskflow@0.0.1 postinstall: `../../../../node_modules/.bin/tsc && rm -rf node_modules/jquery/src && rm -f node_modules/jquery/external/sizzle/dist/sizzle.js && rm -f node_modules/jquery/dist/core.js && mv -f node_modules/jquery/dist/jquery.min.js node_modules/jquery/dist/jquery.js && rm -f node_modules/jquery/dist/jquery.slim* && mv -f node_modules/jquery/dist/jquery.min.map node_modules/jquery/dist/jquery.map && rm -rf node_modules/d3/src && mv node_modules/d3/d3.min.js node_modules/d3/d3.js && rm -f node_modules/elkjs/lib/elk-worker.js node_modules/elkjs/lib/elk.bundled.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @shell/wskflow@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rabbah/.npm/_logs/2018-11-29T20_18_20_166Z-debug.log
npm WARN plugins@1.0.0 No repository field.

added 93 packages in 30.775s

...

> kui-shell@2.0.0 compile /Users/rabbah/projects/kui/app
> if [ -d ../dist ]; then cd ../dist/bin && ./compile.js; fi

  ✓ plugin	apache-composer
  ✓ preload	apache-composer
  ✓ plugin	bash-like
  ✓ plugin	core-support
  ✓ preload	core-support
  ✓ plugin	editor
  ✓ preload	editor
  ✓ plugin	field-installed-plugins
  ✓ plugin	grid
  ✓ plugin	k8s
  ✓ plugin	openwhisk
  ✓ plugin	openwhisk-debug
  ✓ plugin	tutorials
  ✓ preload	tutorials
  ✓ plugin	wskflow
commencing seticon
Using appName=Kui and appIcon=../app/content/icons/png/kui.png

done
added 210 packages in 41.676s
added 291 packages in 56.672s
```

### PR DESCRIPTION
**Pull request by myan9**
app list change
remove @demos/on-forall.js
remove openwhisk-fqn and debug dependency
avoid ts compile errors in wskflow_test/zzz-bottom-bar-back-bottom
change @ibm-functions to openwhisk composer
enable session flow tests

Fixes #5

### CODE REVIEW

File: app/plugins/modules/apache-composer/src/test/composer1/zzz-bottom-bar-back-button.ts [hunk 1]
```diff
@@ -63,10 +63,15 @@ describe('Bottom bar back button functionality', function (this: ISuite) {
...
   const node2 = `${ui.selectors.SIDECAR_CUSTOM_CONTENT} .node.action[data-deployed="deployed"]:nth-of-type(4)`
+
+  const getActionName = (path) => {
+    return path.substring(path.lastIndexOf('/') + 1)
+  }
+
   it('should click on the first node', () => {
     return this.app.client.waitForVisible(node1)
       .then(() => this.app.client.getAttribute(node1, 'data-name'))
-      .then(path => path.substring(path.lastIndexOf('/') + 1))
```
Comment (myan9) [inline app/plugins/modules/apache-composer/src/test/composer1/zzz-bottom-bar-back-button.ts]: ts compile error on `path`: Object is possibly null.
