### PR TITLE
fix(packages/kui-builder): unify the configuration settings to avoid collision

### LINKED ISSUE #2047: Specifying bodyCss value in theme.json is not injected into webpack generated index.html
**Describe the bug**
The new style, `kui--bottom-input`, can be specified as the value for `bodyCss` in the theme.json file for a custom client using webpack. (See this PR https://github.com/IBM/kui/pull/1956) There is code that looks for that style class when rendering the main KUI panel, but that value is not injected into the style list on the <body> tag when the webpack build generates the index.html file.

**Steps to reproduce the behavior**

1. Follow the steps listed here for building a custom client using webpack
2. Go to the client theme/theme.json file and add `"bodyCss": "kui--bottom-input",` to the theme file
3. Build the webpack
4. Display the KUI UI and notice there is no input area at the bottom of the UI panel (and inspect the index.html source to see the `kui--bottom-input` style is not on the <body> tag.
5. If you add that style class to the <body> tag once the page is loaded (via the browser Developer Tools editor), the bottom input area will display, but it does not recognize the user hitting the Enter key after typing a command (probably because that DOM element is not listening for the Enter event if it gets created after the page loads).

**Expected behavior**
The `cssBody` theme.json value should be injected into the generation of index.html by the webpack build.

**System**

- Kui version: latest @dev version
- Operating system: Webpack built on MacOS Mohave

### PR DESCRIPTION
**Pull request by myan9**
Fixes #2047

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Please confirm that your PR fulfills these requirements

- [x] Multiple commits are squashed into one commit.
- [x] The commit message follows [Conventional Commits](https://github.com/IBM/kui/blob/master/CONTRIBUTING.md#conventional-commits), which allows us to autogenerate release notes; e.g. `fix(plugins/plugin-k8s): fixed annoying bugs`
- [x] All npm dependencies are pinned.

### CODE REVIEW

File: packages/kui-builder/lib/configure.js [hunk 1]
```diff
@@ -49,6 +49,40 @@ const readIndex = options =>
...
   })
 
+/**
+ * Unify the given settings of configurations
+ *
+ */
+const unify = (setting1, setting2) => {
+  const uniqe = arr => {
+    return arr.filter((element, index) => arr.indexOf(element) === index)
+  }
```
Comment (myan9) [inline packages/kui-builder/lib/configure.js]: unique() is for webpack-watch. webpack-watch calls configure a couple of times. With my unify, webpack-watch will keep appending duplicated element to array, and error out for duplicated string value.

File: packages/kui-builder/lib/configure.js [hunk 2]
```diff
@@ -49,6 +49,40 @@ const readIndex = options =>
...
+
+  for (const key in setting2) {
+    if (!unifiedSettings[key]) {
+      unifiedSettings[key] = setting2[key]
+    } else {
+      if (Array.isArray(unifiedSettings[key]) && Array.isArray(setting2[key])) {
+        // concatenate the arrays
+        unifiedSettings[key] = unifiedSettings[key].concat(setting2[key])
+        // remove the duplicated elements and join the array into a string
+        unifiedSettings[key] = uniqe(unifiedSettings[key]).join(' ')
```
Comment (myan9) [inline packages/kui-builder/lib/configure.js]: join(' ') is to remove the comma from array concatenation

File: packages/kui-builder/lib/configure.js [hunk 3]
```diff
@@ -49,6 +49,40 @@ const readIndex = options =>
...
+      } else if (!Array.isArray(unifiedSettings[key]) && Array.isArray(setting2[key])) {
+        // split the first string into an array and concatenate the arrays
+        unifiedSettings[key] = unifiedSettings[key].split(' ').concat(setting2[key])
+        // remove the duplicated elements and join the array into a string
+        unifiedSettings[key] = uniqe(unifiedSettings[key]).join(' ')
```
Comment (myan9) [inline packages/kui-builder/lib/configure.js]: ^^^ this is for the case that, at some point, webpack-watch will read bodyCss from the existing index.html and get `bodyCss:'not-electron kui'`.

File: packages/kui-builder/lib/configure.js [hunk 4]
```diff
@@ -49,6 +49,40 @@ const readIndex = options =>
...
+  for (const key in setting2) {
+    if (!unifiedSettings[key]) {
+      unifiedSettings[key] = setting2[key]
+    } else {
+      if (Array.isArray(unifiedSettings[key]) && Array.isArray(setting2[key])) {
+        // concatenate the arrays
+        unifiedSettings[key] = unifiedSettings[key].concat(setting2[key])
+        // remove the duplicated elements and join the array into a string
+        unifiedSettings[key] = uniqe(unifiedSettings[key]).join(' ')
+      } else if (!Array.isArray(unifiedSettings[key]) && Array.isArray(setting2[key])) {
```
Comment (myan9) [inline packages/kui-builder/lib/configure.js]: At some point, webpack-watch will read bodyCss as `bodyCss:'not-electron kui'` (maybe from existing index.html?), so I have to add the case here.
