### PR TITLE
fix: LeftNavSidecar fails silently for MMR with plain text mode

### LINKED ISSUE #3823: LeftNavSidecar fails silently for MMR with plain text mode
For MMR that has plain text mode, `LeftNavSidecar` fails with a blank content page. 
image

This is because `LeftNavSidecar` passed wrong response to `Editor`, and Editor lacks error handling. 

Try the following `NavResponse` to reproduce the error:
```{
  "nav": {
    "Kui": {
      "modes": [
        {
          "mode": "about",
          "content": "test",
          "contentType": "text/plain" // or without contentType
        },
        { "mode": "version", "contentFrom": "version --full" }
      ]
    }
  }
}
```

### PR DESCRIPTION
**Pull request by myan9**
Also improved error handling of Editor

Fixes #3823

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Please confirm that your PR fulfills these requirements

- [x] Multiple commits are squashed into one commit.
- [x] The commit message follows [Conventional Commits](https://github.com/IBM/kui/blob/master/CONTRIBUTING.md#conventional-commits), which allows us to autogenerate release notes; e.g. `fix(plugins/plugin-k8s): fixed annoying bugs`
- [x] All npm dependencies are pinned.

### CODE REVIEW

File: plugins/plugin-sidecar/src/view/components/LeftNavSidecar.tsx [hunk 1]
```diff
@@ -174,7 +174,7 @@ export default class LeftNavSidecar extends BaseSidecar<NavResponse, State> {
         <KuiContent
           tab={this.state.tab}
           mode={this.state.allNavs[navIdx].tabs[tabIdx]}
-          response={this.state.response[navIdx]}
+          response={this.state.response[Object.keys(this.state.response)[navIdx]]}
```
Comment (starpit) [inline plugins/plugin-sidecar/src/view/components/LeftNavSidecar.tsx]: maybe some clarification here? this looks weird, and hard to understand.

Comment (myan9) [reply plugins/plugin-sidecar/src/view/components/LeftNavSidecar.tsx]: solved, thanks!
