### PR TITLE
fix: allow ascii-to-table drilldown effect for `oc` commands (5.1.14)

### LINKED ISSUE #3168: Revert table drilldown effect for `oc` commands

### PR DESCRIPTION
**Pull request by myan9**
Revert "fix(packages/core): broken clickable resource names for CLIs that don't have a kui plugin"
Also white-listed oc comamnds

This reverts commit 39500ba350b7896c831d88d4424affc376a9ed9d.

Fixes #3168

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Please confirm that your PR fulfills these requirements

- [x] Multiple commits are squashed into one commit.
- [x] The commit message follows [Conventional Commits](https://github.com/IBM/kui/blob/master/CONTRIBUTING.md#conventional-commits), which allows us to autogenerate release notes; e.g. `fix(plugins/plugin-k8s): fixed annoying bugs`
- [x] All npm dependencies are pinned.

### CODE REVIEW

File: packages/core/src/webapp/util/ascii-to-table.ts [hunk 1]
```diff
@@ -362,7 +442,7 @@ export const formatTable = (entityType: string, lines: Pair[][]): Table => {
       .map(({ key, value: column, valueDom, css }, colIdx) => ({
         key,
         tag: (idx > 0 && tagForKey[key]) || undefined,
-        onclick: false,
+        onclick: isKube && colIdx + 1 === nameColumnIdx && onclick, // see the onclick comment: above ^^^; +1 because of slice(1)
```
Comment (myan9) [inline packages/core/src/webapp/util/ascii-to-table.ts]: Added `isKube` to `onclick` to white-list `oc`. All the other changes are from reverting commit 39500ba350b7896c831d88d4424affc376a9ed9d .

File: packages/core/src/webapp/util/ascii-to-table.ts [hunk 2]
```diff
@@ -383,7 +463,7 @@ export const formatTable = (entityType: string, lines: Pair[][]): Table => {
       name: nameForDisplay,
       nameDom: columns[0].valueDom,
       fontawesome: idx !== 0 && columns[0].key === 'CURRENT' && 'fas fa-network-wired',
-      onclick: false,
+      onclick: isKube && nameColumnIdx === 0 && onclick, // if the first column isn't the NAME column, no onclick; see onclick below
```
Comment (myan9) [inline packages/core/src/webapp/util/ascii-to-table.ts]: Added isKube to onclick to white-list oc. All other changes are from reverting commit 39500ba .
