### PR TITLE
chore(plugins/plugin-bash-like): improve proxy versus HOME and some plumbing bugs

### LINKED ISSUE #1929: stop using login shell for pty shell subprocesses
login shells can be expensive. we should do this once, on load, and capture `printenv`; then, we inject the environment map into the subprocesses rather than using a login shell

open question: how much does printenv cover of what we need from a login shell? probably most of it, but the risk is that we're losing something vital in return for more responsive kui command execution

### LINKED ISSUE #1952: proxy does not support HOME
the HOME env var is not available to proxied commands

### PR DESCRIPTION
**Pull request by starpit**
improve proxy support for HOME and fix plumbing to subprocess

Fixes #1952

#### My PR is a:

- [ ] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Please confirm that your PR fulfills these requirements

- [x] Multiple commits are squashed into one commit.
- [x] The commit message follows [Conventional Commits](https://github.com/IBM/kui/blob/master/CONTRIBUTING.md#conventional-commits), which allows us to autogenerate release notes; e.g. `fix(plugins/plugin-k8s): fixed annoying bugs`
- [x] All npm dependencies are pinned.

### CODE REVIEW

File: plugins/plugin-bash-like/src/preload.ts [hunk 1]
```diff
@@ -23,14 +23,68 @@ import { CommandRegistrar } from '@kui-shell/core/models/command'
 
 import { preload as registerCatchAll } from './lib/cmds/catchall'
 
+import { getLoginShell, setShellAliases } from './pty/server'
+import { exec } from 'child_process'
+import * as propertiesParser from 'properties-parser'
+function prefetchEnv() {
```
Comment (ydarias) [inline plugins/plugin-bash-like/src/preload.ts]: We could use `promisify` to make the code more readable?

```
const execAsync = promisify(exec)

const prefetchEnv = async () => {
  try {
    const data = await execAsync(`${await getLoginShell()} -l -c printenv`)
    if (data.stderr) {
      console.error(data.stderr)
    } else {
      const env = propertiesParser.parse(data.stdout.toString())
      debug('got env', env)
      for (const key in env) {
        process.env[key] = env[key]
      }
    }
  } catch (err) {
    console.error('Error retrieving shell ENV', err)
  }
}
```

This way we are more consistent in the decision to use async-await.

File: plugins/plugin-bash-like/src/preload.ts [hunk 2]
```diff
@@ -23,14 +23,68 @@ import { CommandRegistrar } from '@kui-shell/core/models/command'
...
+      resolve()
+    })
+  })
+}
+
+function unquote(val: string): string {
+  return val.replace(/(^')|('$)/g, '').replace(/'\\''/g, "'")
+}
+
+function prefetchAliases() {
```
Comment (ydarias) [inline plugins/plugin-bash-like/src/preload.ts]: The same operation with `promisify` could be done here.

```
const prefetchAliases = async () => {
  try {
    const data = await execAsync(`${await getLoginShell()} -l -c alias`)
    if (data.stderr) {
      console.error(data.stderr)
    } else {
      const aliases = data.stdout
        .toString()
        .trim()
        .split(/[\n\r]/)
        .map(_ => _.match(/^(alias )?(.*)=(.*)/))
        .reduce((M, [ignore1, ignore2, key, value]) => {
          M[key] = unquote(value)
          return M
        }, {})
      debug('got aliases', aliases)
      setShellAliases(aliases)
    }
  } catch (err) {
    console.error('Error retrieving shell aliases', err)
  }
}
```

**Comment by starpit** [comment]
thanks! this feature isn't yet enabled. i'll address these comments when the feature is enabled
