### PR TITLE
fix(plugins/plugin-client-common): clicking 'remove' of a watchable response doesn't abort the underlying pty job

### LINKED ISSUE #5090: clicking 'remove' of a watchable response doesn't abort the underlying pty job
E.g. Type command: `k get pods -w`, and click "Remove" in the overflow menu, the underlying pty job doesn't get aborted

### PR DESCRIPTION
**Pull request by myan9**
Fixes #5090

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Please confirm that your PR fulfills these requirements

- [x] Multiple commits are squashed into one commit.
- [x] The commit message follows [Conventional Commits](https://github.com/IBM/kui/blob/master/CONTRIBUTING.md#conventional-commits), which allows us to autogenerate release notes; e.g. `fix(plugins/plugin-k8s): fixed annoying bugs`
- [x] All npm dependencies are pinned.

### CODE REVIEW

File: plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx [hunk 1]
```diff
@@ -537,6 +545,8 @@ export default class ScrollableTerminal extends React.PureComponent<Props, State
     this.setState(curState => {
       const idx = this.findSplit(this.state, sbuuid)
       if (idx >= 0) {
+        curState.splits[idx].blocks.forEach(this.removeWatchableBlock)
```
Comment (starpit) [inline plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx:548]: doesn't this need either a `this.removeWatchableBlock.bind(this)` ? or `block => this.removeWatchableBlock(block)`?

Comment (starpit) [reply plugins/plugin-client-common/src/components/Views/Terminal/ScrollableTerminal.tsx:548]: i guess not? is this a change to nodejs?
